import requests

# Define the API endpoint and the payload
url = "http://localhost:6336/rewriter"
payload = {
    "sql": "select sum(l_extendedprice) / 7.0 as avg_yearly from lineitem, part where p_partkey = l_partkey and p_brand = 'Brand#23' and p_container = 'MED BOX' and l_quantity < ( select 0.2 * avg(l_quantity) from lineitem where l_partkey = p_partkey );",  # Replace with your actual SQL query
    "schema": [
    {
        "table":"partsupp",
        "rows":1000,
        "columns":[
            {
                "name":"ps_partkey",
                "type":"bigint"
            },
            {
                "name":"ps_suppkey",
                "type":"bigint"
            },
            {
                "name":"ps_availqty",
                "type":"bigint"
            },
            {
                "name":"ps_supplycost",
                "type":"decimal"
            },
            {
                "name":"ps_comment",
                "type":"varchar"
            }
        ]
    },
    {
        "table":"orders",
        "rows":1000,
        "columns":[
            {
                "name":"o_orderkey",
                "type":"bigint"
            },
            {
                "name":"o_custkey",
                "type":"bigint"
            },
            {
                "name":"o_orderstatus",
                "type":"char"
            },
            {
                "name":"o_totalprice",
                "type":"decimal"
            },
            {
                "name":"o_orderdate",
                "type":"date"
            },
            {
                "name":"o_orderpriority",
                "type":"char"
            },
            {
                "name":"o_clerk",
                "type":"char"
            },
            {
                "name":"o_shippriority",
                "type":"bigint"
            },
            {
                "name":"o_comment",
                "type":"varchar"
            }
        ]
    },
    {
        "table":"lineitem",
        "rows":1000,
        "columns":[
            {
                "name":"l_orderkey",
                "type":"bigint"
            },
            {
                "name":"l_partkey",
                "type":"bigint"
            },
            {
                "name":"l_suppkey",
                "type":"bigint"
            },
            {
                "name":"l_linenumber",
                "type":"bigint"
            },
            {
                "name":"l_quantity",
                "type":"bigint"
            },
            {
                "name":"l_extendedprice",
                "type":"decimal"
            },
            {
                "name":"l_discount",
                "type":"decimal"
            },
            {
                "name":"l_tax",
                "type":"decimal"
            },
            {
                "name":"l_returnflag",
                "type":"char"
            },
            {
                "name":"l_linestatus",
                "type":"char"
            },
            {
                "name":"l_shipdate",
                "type":"date"
            },
            {
                "name":"l_commitdate",
                "type":"date"
            },
            {
                "name":"l_receiptdate",
                "type":"date"
            },
            {
                "name":"l_shipinstruct",
                "type":"char"
            },
            {
                "name":"l_shipmode",
                "type":"char"
            },
            {
                "name":"l_comment",
                "type":"varchar"
            }
        ]
    },
    {
        "table":"customer",
        "rows":1000,
        "columns":[
            {
                "name":"c_custkey",
                "type":"bigint"
            },
            {
                "name":"c_name",
                "type":"varchar"
            },
            {
                "name":"c_address",
                "type":"varchar"
            },
            {
                "name":"c_nationkey",
                "type":"bigint"
            },
            {
                "name":"c_phone",
                "type":"char"
            },
            {
                "name":"c_acctbal",
                "type":"decimal"
            },
            {
                "name":"c_mktsegment",
                "type":"char"
            },
            {
                "name":"c_comment",
                "type":"varchar"
            }
        ]
    },
    {
        "table":"part",
        "rows":1000,
        "columns":[
            {
                "name":"p_partkey",
                "type":"bigint"
            },
            {
                "name":"p_name",
                "type":"varchar"
            },
            {
                "name":"p_mfgr",
                "type":"char"
            },
            {
                "name":"p_brand",
                "type":"char"
            },
            {
                "name":"p_type",
                "type":"varchar"
            },
            {
                "name":"p_size",
                "type":"bigint"
            },
            {
                "name":"p_container",
                "type":"char"
            },
            {
                "name":"p_retailprice",
                "type":"decimal"
            },
            {
                "name":"p_comment",
                "type":"varchar"
            }
        ]
    },
    {
        "table":"region",
        "rows":1000,
        "columns":[
            {
                "name":"r_regionkey",
                "type":"bigint"
            },
            {
                "name":"r_name",
                "type":"char"
            },
            {
                "name":"r_comment",
                "type":"varchar"
            }
        ]
    },
    {
        "table":"nation",
        "rows":1000,
        "columns":[
            {
                "name":"n_nationkey",
                "type":"bigint"
            },
            {
                "name":"n_name",
                "type":"char"
            },
            {
                "name":"n_regionkey",
                "type":"bigint"
            },
            {
                "name":"n_comment",
                "type":"varchar"
            }
        ]
    },
    {
        "table":"supplier",
        "rows":1000,
        "columns":[
            {
                "name":"s_suppkey",
                "type":"bigint"
            },
            {
                "name":"s_name",
                "type":"char"
            },
            {
                "name":"s_address",
                "type":"varchar"
            },
            {
                "name":"s_nationkey",
                "type":"bigint"
            },
            {
                "name":"s_phone",
                "type":"char"
            },
            {
                "name":"s_acctbal",
                "type":"bigint"
            },
            {
                "name":"s_comment",
                "type":"varchar"
            }
        ]
    }
]
}
# print("Sending payload:", payload)  # Debug line to check the payload
# Make the POST request
try:
    response = requests.post(url, json=payload)
    response.raise_for_status()
    print("Response from API:", response.json())
except requests.exceptions.RequestException as e:
    print("An error occurred:", e)
    print("Response text:", response.text)  # Print the full response for additional error details
